baseURL = "https://quarcs-lab.org/"
languageCode = "en-us"
title = "QuaRCS-lab Network"
theme = "timer-hugo"

# We Used Ionicons Icon font for Icon, for more details check this link - https://ionicons.com/

# Navbar Menus
[[menu.main]]
name    = "People"
url     = "about"
weight  = 20
[[menu.main]]
name    = "Research"
url     = "research"
weight  = 40
[[menu.main]]
name    = "Events"
#url     = "portfolio/webinars"
url     = "https://lu.ma/quarcs"
weight  = 43
#[[menu.main]]
#name    = "Learning"
#url     = "portfolio/webinars"
#url     = "https://discord.gg/NKb5GJJmkd"
#weight  = 50
[[menu.main]]
name    = "Tutorials"
url     = "portfolio/data-tutorials"
weight  = 60
#[[menu.main]]
#name    = "Projects"
#url     = "service"
#weight  = 80
[[menu.main]]
name    = "Community"
url     = "https://discord.gg/pfEmxwSEHy"
weight  = 45
[[menu.main]]
name    = "Github"
url     = "https://github.com/quarcs-lab"
weight  = 90
[[menu.main]]
name    = "Contact"
url     = "https://carlos-mendez.rbind.io/#contact"
weight  = 95

# Site Params
[params]
home = "Home"
logo = "images/logo.png"
dateFormat = "6 January 2006"
# Meta data
description = "Airspace Hugo theme"
author = "Themefisher"
# Google Analitycs
googleAnalitycsID = "Your ID"
# contact form action
contactFormAction = "#" # contact form works with https://formspree.io


# Homepage About Section
[params.about]
enable  = true
title   = "ABOUT US"
content = "In the QuaRCS network, we conduct research on quantitative regional and computational science. We exploit the integration of development economics, spatial data science, and econometrics to understand and inform the process of sustainable development across subnational regions and countries. <br> <br> The QuaRCS network is also part of the UN Sustainable Development Solutions Network (SDSN). As such, it helps mobilize scientific knowledge and technological expertise to promote global sustainable development."
image   = "images/about/about.png"


# Banner Section
[params.banner]
enable  = true
bgImage = "images/slider7.jpg"
heading = "We conduct research about"
description = "Quantitative Regional and Computational Science"
# button
btn     = true
btnText = "Research Projects and Outcomes"
btnURL  = "research"

# flip text
[[params.banner.flipText]]
title   = "Regional Inequality"
[[params.banner.flipText]]
title   = "Regional Growth"
[[params.banner.flipText]]
title   = "The Geography of Development"
[[params.banner.flipText]]
title   = "Economic and Social Convergence"
[[params.banner.flipText]]
title   = "Economic Growth and Structural Change"


# Call to Action
[params.cta]
enable  = true
title   = "Do you conduct similar research?"
content = "Join our research and learning community"
btnText = "JOIN US"
btnURL  = "https://discord.gg/pfEmxwSEHy"

# Portfolio Section On Homepage
[params.portfolio]
enable  = true
title   = "Activities"
subtitle= ""

# social icon
[[params.socialIcon]]
icon = "ion-social-facebook"
url = "https://discord.gg/pfEmxwSEHy"

#[[params.socialIcon]]
#icon = "ion-social-instagram"
#url = "#"

#[[params.socialIcon]]
#icon = "ion-social-linkedin"
#url = "#"
