baseURL = "https://quarcs-lab.org/"
languageCode = "en-us"
title = "QuaRCS-lab Network"
theme = "timer-hugo"

# We Used Ionicons Icon font for Icon, for more details check this link - https://ionicons.com/

# Navbar Menus
[[menu.main]]
name    = "People"
url     = "about"
weight  = 20
[[menu.main]]
name    = "Research"
url     = "research"
weight  = 40
[[menu.main]]
name    = "Webinars"
url     = "portfolio/webinars"
weight  = 50
[[menu.main]]
name    = "Data"
url     = "portfolio/data-tutorials"
weight  = 60
[[menu.main]]
name    = "Community"
url     = "https://forms.gle/4aQyEfMqZ4bLscCU7"
weight  = 70
#[[menu.main]]
#name    = "Projects"
#url     = "service"
#weight  = 80
[[menu.main]]
name    = "Events"
url     = "https://lu.ma/quarcs"
weight  = 45
[[menu.main]]
name    = "Github"
url     = "https://github.com/quarcs-lab"
weight  = 90
[[menu.main]]
name    = "Contact"
url     = "https://carlos-mendez.rbind.io/#contact"
weight  = 95

# Site Params
[params]
home = "Home"
logo = "images/logo.png"
dateFormat = "6 January 2006"
# Meta data
description = "Airspace Hugo theme"
author = "Themefisher"
# Google Analitycs
googleAnalitycsID = "Your ID"
# contact form action
contactFormAction = "#" # contact form works with https://formspree.io


# Homepage About Section
[params.about]
enable  = true
title   = "ABOUT US"
content = "In the QuaRCS lab, we exploit the integration of econometrics, data science, and machine learning methods to understand and inform the process of economic growth and development of countries, regions, and industries. <br> <br> The QuaRCS lab is also a member of the UN Sustainable Development Solutions Network (SDSN). As such, it helps mobilize scientific knowledge and technological expertise to promote global sustainable development.  "
image   = "images/about/about.png"


# Banner Section
[params.banner]
enable  = true
bgImage = "images/slider7.jpg"
heading = "We conduct research about"
description = "Quantitative Regional and Computational Science"
# button
btn     = true
btnText = "Research Projects and Outcomes"
btnURL  = "research"

# flip text
[[params.banner.flipText]]
title   = "Regional Inequality"
[[params.banner.flipText]]
title   = "Regional Growth"
[[params.banner.flipText]]
title   = "Geography of Development"
[[params.banner.flipText]]
title   = "Economic and Social Convergence"
[[params.banner.flipText]]
title   = "Labor markets and macroeconomic shocks"
[[params.banner.flipText]]
title   = "Economic growth and structural change"


# Call to Action
[params.cta]
enable  = true
title   = "Do you conduct similar research?"
content = "Join our mailing list and get in touch with us"
btnText = "JOIN US"
btnURL  = "https://lu.ma/quarcs"

# Portfolio Section On Homepage
[params.portfolio]
enable  = true
title   = "Activities"
subtitle= ""

# social icon
[[params.socialIcon]]
icon = "ion-social-facebook"
url = "https://www.facebook.com/groups/QuaRCS.Lab/"

#[[params.socialIcon]]
#icon = "ion-social-instagram"
#url = "#"

#[[params.socialIcon]]
#icon = "ion-social-linkedin"
#url = "#"
